vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    post:
    #        uri_prefix: /images/post
    #        upload_destination: '%kernel.project_dir%/public/images/post'
