easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        help: 'The items in this entity can NOT be deleted here, delete it in Comments before'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','userName','userEmail','userPassword','createdAt','posts']
      form:
        fields:
          - {property: 'userName'}
          - {property: 'userEmail'}
          - {property: 'userPassword'}
          - {property: 'createdAt'}
          - {property: 'posts'}

